export const PERMISSIONS = {
  ALL: '*',
  DASHBOARD_READ: 'dashboard:read',
  REPORT_READ: 'report:read',
  NOTIFICATION_READ: 'notification:read',
  MOVIE_CREATE: 'movie:create',
  MOVIE_READ: 'movie:read',
  MOVIE_UPDATE: 'movie:update',
  MOVIE_DELETE: 'movie:delete',
  CINEMA_CREATE: 'cinema:create',
  CINEMA_READ: 'cinema:read',
  CINEMA_UPDATE: 'cinema:update',
  CINEMA_DELETE: 'cinema:delete',
  HALL_CREATE: 'hall:create',
  HALL_READ: 'hall:read',
  HALL_UPDATE: 'hall:update',
  HALL_DELETE: 'hall:delete',
  SEAT_CREATE: 'seat:create',
  SEAT_READ: 'seat:read',
  SEAT_UPDATE: 'seat:update',
  SEAT_DELETE: 'seat:delete',
  SHOWTIME_CREATE: 'showtime:create',
  SHOWTIME_READ: 'showtime:read',
  SHOWTIME_UPDATE: 'showtime:update',
  SHOWTIME_DELETE: 'showtime:delete',
  BOOKING_CREATE: 'booking:create',
  BOOKING_READ: 'booking:read',
  BOOKING_UPDATE: 'booking:update',
  BOOKING_DELETE: 'booking:delete',
  PAYMENT_CREATE: 'payment:create',
  TICKET_READ: 'ticket:read',
  TICKET_UPDATE: 'ticket:update',
  USER_CREATE: 'user:create',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
